### ISSUE TITLE
find similar within DB for a query

### ISSUE THREAD

**Issue by reisner** [dselivanov/LSHR#17]
From what I understand, the `get_similar_pairs_cosine` function finds pairs within a dataset. However, what if we are finding similarity between a query and the dataset? Would be nice to have this functionality here. Do you have plans to update this package, or know of others that do this?

**Comment by dselivanov** [comment]
No plans for that. How big is the query? May be it makes sense to compute
exact similarity between query and db? This is a matter of a one matrix
multiplication.

пт, 16 авг. 2019 г., 20:52 Roman Eisner <notifications@github.com>:

**Comment by reisner** [comment]
Yeah, it's just a single query, but a very large DB. I would like it to be quick, in realtime. Problem is the database is going to be 10s of millions of rows, and this starts to be slow at this point.

**Comment by dselivanov** [comment]
My suggestion is to benchmark. As I remember I had similar task - query
against 20m book titles. And I've started to build LSH based retrieval. But
at the end switched to brute force since it was faster.

пт, 16 авг. 2019 г., 20:59 Roman Eisner <notifications@github.com>:

**Comment by reisner** [comment]
Oh, I did benchmark, that's why I'm here :) No problem if you're not planning on implementing this, thanks!

**Comment by dselivanov** [comment]
Is your db sparse or dense matrix?

**Comment by reisner** [comment]
dense matrix, it's a word embedding database.

**Comment by dselivanov** [comment]
That's easy then - take a look to rcppannoy or https://github.com/jlmelville/rcpphnsw

**Comment by reisner** [comment]
Thanks for that!
